# Generated by Django 2.0.7 on 2018-07-02 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_m', models.CharField(max_length=100)),
                ('apellido_m', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='OrdenLaboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('examen', models.CharField(max_length=100)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emitirorder.Medico')),
            ],
            options={
                'verbose_name_plural': 'OrdenLaboratorio',
            },
        ),
    ]
